// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj-AdzvN34JkTaKNaJKLMDPrREAw0K2-A',
    appId: '1:937565148047:web:ab3b711c9572649773f1fa',
    messagingSenderId: '937565148047',
    projectId: 'madsm-ff701',
    authDomain: 'madsm-ff701.firebaseapp.com',
    storageBucket: 'madsm-ff701.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYnjq6RLFEGm2wfXO2jGUfEOrGDNJWzc',
    appId: '1:937565148047:android:c19436eede63f76673f1fa',
    messagingSenderId: '937565148047',
    projectId: 'madsm-ff701',
    storageBucket: 'madsm-ff701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPFl-rJchKQwc7jCsYqaJu63wQktf1JU',
    appId: '1:937565148047:ios:a57fd366b76eacfd73f1fa',
    messagingSenderId: '937565148047',
    projectId: 'madsm-ff701',
    storageBucket: 'madsm-ff701.firebasestorage.app',
    iosBundleId: 'com.hiutin.madsm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvPFl-rJchKQwc7jCsYqaJu63wQktf1JU',
    appId: '1:937565148047:ios:d7bd57ee1a36375373f1fa',
    messagingSenderId: '937565148047',
    projectId: 'madsm-ff701',
    storageBucket: 'madsm-ff701.firebasestorage.app',
    iosBundleId: 'com.henry.flutterMvvmRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj-AdzvN34JkTaKNaJKLMDPrREAw0K2-A',
    appId: '1:937565148047:web:50438ad2a1a3161873f1fa',
    messagingSenderId: '937565148047',
    projectId: 'madsm-ff701',
    authDomain: 'madsm-ff701.firebaseapp.com',
    storageBucket: 'madsm-ff701.firebasestorage.app',
  );
}
